### ISSUE TITLE
slack-export-viewer doesnt work with recent version of werkzeug

### ISSUE THREAD

**Issue by harpomaxx** [hfaran/slack-export-viewer#157]
I've installed `slack-export-viewer` using `pip` and `pipx` and in both cases, I've got the error
```
Traceback (most recent call last):
  File "/home/harpo/.local/bin/slack-export-viewer", line 8, in <module>
    sys.exit(main())
  File "/home/harpo/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/harpo/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/harpo/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harpo/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/harpo/.local/lib/python3.8/site-packages/slackviewer/main.py", line 63, in main
    configure_app(app, archive, channels, no_sidebar, no_external_references, debug)
  File "/home/harpo/.local/lib/python3.8/site-packages/slackviewer/main.py", line 26, in configure_app
    top.channels = reader.compile_channels(channels)
AttributeError: 'LocalStack' object has no attribute 'channels'
```
Looking at stackoverflow I found a mention about [this](https://stackoverflow.com/questions/71695691/flask-app-ctx-stack-ident-func-error-due-to-ident-func-deprecated-in-we) similar issue.
It seems that has something to do with a recent update to the `werkzeug` library. As suggested in at StackOverflow  I forced the installation of  a previous version of `werkzeug` 
```
pip3 install werkzeug==v2.0.3 
```
and now it is working perfectly !!!

**Comment by Damnum** [comment]
@harpomaxx did you do anything else? I've installed werkzeug 2.0.3 and I'm still getting the same error

**Comment by MakingSpiderSense** [comment]
Worked for me after installing 2.0.3. Thanks!

**Comment by stiltr** [comment]
Worked for me with:
`pipx runpip slack-export-viewer install werkzeug==v2.0.3`

**Comment by ronnydw** [comment]
Thanks @stiltr , indeed it works with werkzeug v2.0.3. I tried with werkzeug v2.2.0 which didn't work

**Comment by k-y** [comment]
For anyone else who stumbles upon this in 2023+, in order for this combination to work, you'll need:
flask==2.1.3
werkzeug==2.0.3

**Comment by hfaran** [comment]
Latest version pinned to <3.0.0 so this shouldn't happen anymore
